### PR TITLE
T286725: Use screen-sized images

### PR DESCRIPTION
**Pull request by medied**
https://phabricator.wikimedia.org/T286725

To reduce memory usage, we can grab just the title strings with `media-list` and then use those to fetch the screen-sized image directly from `Gallery`. Tested on my device: a bit slower (yours too?) but lighter on memory. Is it worth adding a little loading UI in between images?

### CODE REVIEW

**Review by hueitan — CHANGES_REQUESTED** [review]
we can reuse the `getArticleMediaInfo` api, then we no longer need to load it when press `ABOUT`

**Comment by stephanebisson** [comment]
This PR makes no difference for memory usage on my Jio1 device. But I'm also not able to see high memory usage on that device.

**Comment by hueitan** [comment]
I think the only thing missing is the loading animation to make it feel better, it's already in [another task](https://phabricator.wikimedia.org/T253466).

**Comment by jpita** [comment]
loaded all the images from the gallery in the Obama article and got 50/60 values

**Comment by medied** [comment]
> loaded all the images from the gallery in the Obama article

@jpita could you please also run the same test and share the values you are getting when running the test in `main` branch so that we may compare between the two branches?

**Comment by jpita** [comment]
> @jpita could you please also run the same test and share the values you are getting when running the test in `main` branch so that we may compare between the two branches?

it's the same, basically.
these are the numbers that go from: 
1- opening the app
2- searching for "obama"
3- selecting barack obama article
4- open the gallery and start going through the images


```
TIME USS PSS
13:06:43 12.7 18.0
13:06:44 12.7 18.0
13:06:45 12.7 18.0
13:06:46 12.7 18.0
13:06:47 15.1 20.4
13:06:48 16.2 21.7
13:06:49 16.8 22.4
13:06:50 16.8 22.4
13:06:51 16.8 22.4
13:06:52 16.8 22.4
13:06:53 16.8 22.4
13:06:54 16.8 22.4
13:06:55 16.8 22.4
13:06:56 20.0 25.6
13:06:57 19.0 24.5
13:06:59 22.1 27.7
13:07:00 24.7 30.0
13:07:01 25.6 31.0
13:07:02 21.0 26.4
13:07:03 21.1 26.4
13:07:04 22.7 28.1
13:07:05 28.8 34.2
13:07:06 36.4 41.8
13:07:07 40.3 45.8
13:07:08 43.7 49.1
13:07:09 42.8 48.3
13:07:10 42.8 48.3
13:07:11 46.3 51.8
13:07:13 44.2 49.7
13:07:14 45.9 51.4
13:07:15 48.1 53.6
13:07:16 51.1 56.6
13:07:17 51.7 57.2
13:07:18 52.0 57.5
13:07:19 54.4 59.9
13:07:20 56.4 61.8
13:07:21 56.4 61.8
13:07:22 58.3 63.7
13:07:23 58.3 63.7
```

**Comment by stephanebisson** [comment]
UPDATE: on my Jio1 device, this tops at around 60 and the baseline is around 80 so I'm going to call this significantly helpful.

**Pull request merged**
