### PR TITLE
Run banana check in CI to prevent introduction of undocumented keys

### PR DESCRIPTION
**Pull request by stephanebisson**

### CODE REVIEW

**Comment by stephanebisson** [comment]
4 messages lack documentation in qqq.json.
Message "content-license" lacks documentation in qqq.json.
Message "suggested-articles" lacks documentation in qqq.json.
Message "toc-footer" lacks documentation in qqq.json.
Message "view-in-browser" lacks documentation in qqq.json.

**Comment by stephanebisson** [comment]
@hueitan can I let you continue this PR?

**Comment by hueitan** [comment]
sure

**Comment by hueitan** [comment]
Thanks

**Pull request merged**
