### PR TITLE
Update onboarding based on new design spec

### PR DESCRIPTION
**Pull request by hueitan**
Phabricator Link: https://phabricator.wikimedia.org/T236304

### Note

| Portrait | Landscape |
| --- | --- |
|Screen Shot 2020-03-04 at 21 38 22|Screen Shot 2020-03-04 at 21 38 25|
|Screen Shot 2020-03-04 at 21 38 30|Screen Shot 2020-03-04 at 21 38 32
|Screen Shot 2020-03-04 at 21 38 39|Screen Shot 2020-03-04 at 21 38 41

### CODE REVIEW

**Comment by jpita** [comment]
@hueitan do u want me to change the spec or is something else going to be added?
right now it seems that we're missing the last page, is it being deleted?

**Comment by hueitan** [comment]
@jpita this is a draft pr, not ready to be reviewed and tested. hold on

**Comment by jpita** [comment]
oh.
don't you prefer to not push anything into github until you have something
working?
first time I see anyone create a PR with a work in progress branch...
_______________________________________
Best Regards,

Jose Pita
linkedin.com/in/pitajose

**Comment by hueitan** [comment]
I did it intentionally to show people what's going on here, that's the feature of how "Draft" work in GitHub.

**Comment by hueitan** [comment]
@jpita ready for the test spec update.

**Comment by jpita** [comment]
oops, merged too soon @hueitan ?

**Comment by hueitan** [comment]
oopss, too fast, @medied do you mind quickly checkout this PR?

**Comment by medied** [comment]
Code changes LGTM!

**Comment by jpita** [comment]
https://media.giphy.com/media/EDt1m8p5hqXG8/source.gif

**Pull request merged**
