### PR TITLE
Include the circleci build number in the app version

### PR DESCRIPTION
**Pull request by stephanebisson**
Phabricator Link: -

### Problem Statement

I don't know which version of the app is published to the store.

### Solution

Include the CircleCI build number as the 4th digit of the version.

### CODE REVIEW

**Comment by medied** [comment]
> Include the CircleCI build number as the 4th digit of the version.

Do we need this to be true everywhere `appVersion` is recorded? (consent.js, sendFeedback.js, etc) Or is 3 digit version enough in other cases?

**Comment by stephanebisson** [comment]
> > Include the CircleCI build number as the 4th digit of the version.
> 
> Do we need this to be true everywhere `appVersion` is recorded? (consent.js, sendFeedback.js, etc) Or is 3 digit version enough in other cases?

It would probably be best to have the same version captured everywhere. Maybe I can just encapsulate that into `appVersion()` so it is used everywhere.

**Comment by hueitan** [comment]
Ideally, once we release our first version `1.0.0`, every release after will need to increment the version digit.

Do you sitll need the build number if we strictly follow the version rule?

**Comment by stephanebisson** [comment]
> Ideally, once we release our first version `1.0.0`, every release after will need to increment the version digit.
> 
> Do you still need the build number if we strictly follow the version rule?

Relying on the package version alone is awkward because we can't go back and pick a build to release. We have to decide to release, change the version, wait for it to build and pick this one. After that, we don't know if we released the first or any other build with that version number. For example, we can't pick the build just before a big risky feature was merged.

Using the CI build number guarantees that each build is unique and identifiable. 

We should still use a versioning scheme to identify work phases (minor, major).

**Pull request merged**
