### PR TITLE
Upgrade banana-i18n version to 2.0.0

### PR DESCRIPTION
**Pull request by hueitan**
Phabricator Link: https://phabricator.wikimedia.org/T262596

I can't reproduce the error, and this is what I found and possibly to prevent the error

### CODE REVIEW

**Review by stephanebisson — CHANGES_REQUESTED** [review]
Banana v1.3.0 is buggy. We can't open the reference popup.

**Comment by hueitan** [comment]
> Banana v1.3.0 is buggy. We can't open the reference popup.

hmmm let me look into that

**Comment by hueitan** [comment]
I have opened the issue from `banana-i18n` https://github.com/wikimedia/banana-i18n/issues/40, does it worth if we change all to have the form in `\\[\\]`?

**Comment by stephanebisson** [comment]
> I have opened the issue from `banana-i18n` [wikimedia/banana-i18n#40](https://github.com/wikimedia/banana-i18n/issues/40), does it worth if we change all to have the form in `\\[\\]`?

There's already an issue where this is discussed: https://github.com/wikimedia/banana-i18n/issues/37

Santhosh said he would produce a new release where special parsing of `[]` can be disabled (or is disabled by default). We will upgrade to that version when it is released.

Let's not do `\\[\\]` in the message. We could do a string replace on the message before passing it to `i18n` temporarily as a quick fix but we would need a comment and maybe a task to make sure we go back to fixing it properly.

**Comment by hueitan** [comment]
> > I have opened the issue from `banana-i18n` [wikimedia/banana-i18n#40](https://github.com/wikimedia/banana-i18n/issues/40), does it worth if we change all to have the form in `\\[\\]`?
> 
> There's already an issue where this is discussed: [wikimedia/banana-i18n#37](https://github.com/wikimedia/banana-i18n/issues/37)
> 
> Santhosh said he would produce a new release where special parsing of `[]` can be disabled (or is disabled by default). We will upgrade to that version when it is released.

Thanks, I just know there are issue and progress on this! 

> We could do a string replace on the message before passing it to `i18n` temporarily as a quick fix but we would need a comment and maybe a task to make sure we go back to fix it properly.

Let's not doing this, going through all the messages before passing to banana is too expensive, i would rather wait for the fix.

**Comment by stephanebisson** [comment]
banana-i18n v2.0.0 is out. It has parsing of `[]` disabled by default and should fix the production error from the linked task. We can update this PR to use it.

**Pull request merged**
