### PR TITLE
Logo change in search.js

### PR DESCRIPTION
**Pull request by Alik-Kumar-Ghosh**
Phabricator Link: https://phabricator.wikimedia.org/project/view/4301/

### Problem Statement

_Logo change in search.js  (Home Page)_

### Solution

_Logo Change for Home page_
image

### CODE REVIEW

**Comment by hueitan** [comment]
@Alik-Kumar-Ghosh Can you explain the changes?

**Comment by Alik-Kumar-Ghosh** [comment]
@hueitan i have changed the home page W logo with Wikipedia logo (112px.png).

**Comment by jpita** [comment]
package-lock.json file was changed as well

**Comment by Alik-Kumar-Ghosh** [comment]
@jpita package-lock.json is system depended it changes according to your system config for npm install

**Pull request closed without merging**
