### PR TITLE
Fix image gallery rendering

### PR DESCRIPTION
**Pull request by stephanebisson**
Phabricator Link: https://phabricator.wikimedia.org/T247260

### Problem Statement

Some images render on top of each other or on top of article text.

### Solution

Rename `.gallery` to `.gallery-view` so it doesn't conflict with the `.gallery` class used in articles. Also adjust margin and position.

### CODE REVIEW

**Comment by soham4abc** [comment]
Looks great for me. Should this be merged?

**Comment by hueitan** [comment]
> Looks great for me. Should this be merged?

yes, normally we wait until QA to do the final test before merge unless there is a breaking change or urgent. It will be great also for others to do the extra test at the same time.

**Comment by soham4abc** [comment]
Cause I am new, just want to get more familiar with the people and the rules. Will be happy enough to make whatever valuable contribution that I can!

**Comment by stephanebisson** [comment]
> Cause I am new, just want to get more familiar with the people and the rules. Will be happy enough to make whatever valuable contribution that I can!

You can contact me at sbisson at wikimedia dot org to discuss how you can help.

**Comment by soham4abc** [comment]
> > Cause I am new, just want to get more familiar with the people and the rules. Will be happy enough to make whatever valuable contribution that I can!
> 
> You can contact me at sbisson at wikimedia dot org to discuss how you can help.

Okay I will get in touch with you.

**Pull request merged**
