### PR TITLE
Read canonical title when it's available in article preview

### PR DESCRIPTION
**Pull request by hueitan**
to avoid redirection, we get the actual title 

see https://phabricator.wikimedia.org/T242350#5816578

### CODE REVIEW

**Comment by stephanebisson** [comment]
Please provide an example of an API url that, when fetched using CORS, doesn't redirect correctly but provides the right canonical title.

**Comment by hueitan** [comment]
load the article `Fassala`, when fetching the summary title `Hodh_Ech Chargui` `https://en.wikipedia.org/api/rest_v1/page/summary/Hodh_Ech Chargui`, it returns the canonical title in `Hodh_Ech_Chargui_Region`, so we know this is the title used to fetch article instead of `Hodh_Ech Chargui`

**Comment by hueitan** [comment]
@stephanebisson not sure whether you can see the different, as you are in the region that api redirect doesn't always work correctly.

**Comment by stephanebisson** [comment]
If you fetch "Hodh_Ech Chargui" and the canonical field contains "Hodh_Ech Chargui_Region", it is because the redirect worked for you and the URL you fetched is actually ".../Hodh_Ech Chargui_Region". 

The redirect issue is not really region-specific as other people have seen it from other places.

I'll merge this now. It doesn't resolve the main issue but it helps propagate the new title when the redirect does work.

**Pull request merged**
