### PR TITLE
Use mobile-html instead of mobile-section

### PR DESCRIPTION
**Pull request by stephanebisson**
Phabricator Link: https://phabricator.wikimedia.org/T272091

### Problem Statement

The `mobile-sections` API is (or soon to be) deprecated. 

To do
 - [x] Reference Preview 4e396c829bf63d72a9a8ad2355a2d1adf0033c7a
 - [x] Show Image in Article, don't forget the group image as well 5b3b3fba768934fe934c8ffd08777a076c04f37d
 - [x] Table 2c58331be93330e3425a4004f8787227072d33b6
 - [x] Missing language count 8fd778c7a0aa0eab2cfa56994c53a3998084e46f
 - [x] toc anchor sometimes doesn't work (http://localhost:8080/#/article/en/Brindle) 440a1c2d65fd2fbda9d469cc52b3055ca442d5ee
 - [x] Instrumentation fail in article page 5b3b3fba768934fe934c8ffd08777a076c04f37d
 - [x] Cleanup legacy code f339f6ec23018d78659c93fd808041ac29fa8063

Other special case
 - [x] unable to load article `en/Retractable_claws` `en/Felid%2C_Iran` (no decription) 32634b9c95a5a78b38ea47aa42aa8b10a30a8fe6
 - [x] Jump to sub section doesn't work (character C quickfact) 43d25c7ad67f7c8fcdb5592b2257d774ef6994fe
 - [x] <s>Jump to sub section (Holly case)</s> Skip this case for now
 - [x] fail to load lot of the articles in device, but able to load in browser (ex. Cat) 2c5d7de6a42332a3314bc79fba6a65cbfe4e5162
 - [x] lead image size issue c2273f2df2e04236b2530754c85caf940e2b89e9
 
### Solution

Try migrating to `mobile-html`, figure out any blocker, see if it looks better.

### Note

Try it out here: https://wikimedia.github.io/wikipedia-kaios/T272091-mobile-html2/sim.html

Comment to this spike is here : https://phabricator.wikimedia.org/T272091#6939336
How to parse the html : https://phabricator.wikimedia.org/T272091#6979185

### CODE REVIEW

**Comment by hueitan** [comment]
Mark this ready for code-review and test, do expect more bug found and fixed at the same time.

**Comment by medied** [comment]
When testing this on device, I think the main thing that pops out at me is that rendering the articles _feels_ a bit slower... mostly because of the [image size issue](https://phabricator.wikimedia.org/T272091#6895468), I believe

**Comment by stephanebisson** [comment]
We'll keep the branch but not merge the PR.

**Review by medied — APPROVED** [review]
LGTM!

**Pull request merged**
