### PR TITLE
Softkey reducer pop event

### PR DESCRIPTION
**Pull request by hueitan**
Phabricator Link: https://phabricator.wikimedia.org/T246146

### Problem Statement

When using the `closeAll` in popup component, the softkey doesn't clean correctly

### Solution

Whenever the component is being unmounted or softkey pop event, find the parent component and do the counting minus until remove it from the stack list

### Note

Please test it carefully

### CODE REVIEW

**Comment by medied** [comment]
FYI: I `git cherry-pick` commit 7090aee28c65208ddd07e2170acc83cc5024dca4 into this branch `T246146-softkey-pop` to be able to test appropriately

**Comment by hueitan** [comment]
@medied next time you can merge the latest master so you will have all updated 👍

**Comment by hueitan** [comment]
@jpita you can add the test here, and the original ticket and the scenario is here https://phabricator.wikimedia.org/T244568

**Comment by jpita** [comment]
I'm seeing this error on the `C` article
image

**Comment by hueitan** [comment]
@jpita can you try again?

**Comment by jpita** [comment]
@hueitan same issue

**Comment by jpita** [comment]
> @jpita you can add the test here, and the original ticket and the scenario is here https://phabricator.wikimedia.org/T244568

this is not working correctly on the device.
the popup shows the text of the article itself instead of the section "related characters"

**Comment by hueitan** [comment]
> > @jpita you can add the test here, and the original ticket and the scenario is here https://phabricator.wikimedia.org/T244568
> 
> this is not working correctly on the device.
> the popup shows the text of the article itself instead of the section "related characters"

true, checking it now.

**Comment by jpita** [comment]
are we waiting for something here?

**Comment by hueitan** [comment]
Let’s merge this, I will file another ticket for this fix

**Pull request merged**
