### PR TITLE
check languageCount in article page

### PR DESCRIPTION
**Pull request by hueitan**

### CODE REVIEW

**Comment by jpita** [comment]
@hueitan  on [this](http://127.0.0.1:8080/#/article/en/Line%20of%20succession%20to%20the%20british%20throne) article, when I try to change the language it still fails.
according to [this](https://phabricator.wikimedia.org/T234628#5790122) comment, this should be fixed here, correct?

**Comment by hueitan** [comment]
@jpita this is because there isn't redirect from our side, it should have the lang links

`http://127.0.0.1:8080/#/article/en/Line%20of%20succession%20to%20the%20british%20throne` 
should redirect to 
`http://127.0.0.1:8080/#/article/en/Succession%20to%20the%20British%20throne`

Ideally, you won't be able to log in to this page if the language count is 0.

**Comment by jpita** [comment]
> @jpita this is because there isn't redirect from our side, it should have the lang links
> 
> `http://127.0.0.1:8080/#/article/en/Line%20of%20succession%20to%20the%20british%20throne`
> should redirect to
> `http://127.0.0.1:8080/#/article/en/Succession%20to%20the%20British%20throne`
> 
> Ideally, you won't be able to log in to this page if the language count is 0.

is this going to be fixed on this PR or a different one?
what about https://phabricator.wikimedia.org/T242350, can I close it or wait for a fix for this issue?

**Comment by hueitan** [comment]
> is this going to be fixed on this PR or a different one?
> what about https://phabricator.wikimedia.org/T242350, can I close it or wait for a fix for this issue?

That will be a different one, I suggest don't wait for it.

**Pull request merged**
